### ISSUE TITLE
dumping list of strings 

### ISSUE THREAD

**Issue by swiss484** [asottile/aspy.yaml#11]
Hi anthony,

I'm trying to read, modify and write pre-commit yaml files and the lists keep getting messed up. Do you know what I'm doing wrong? 

```python
import io
from aspy.yaml import ordered_dump
from aspy.yaml import ordered_load
PRE_COMMIT_YAML = '.pre-commit-config.yaml'

config_data = ordered_load(io.open(PRE_COMMIT_YAML).read())
YAML_DUMP_KWARGS = {
    'default_flow_style': False,
    # Use unicode
    'encoding': None,
    'indent': 4,
}
with io.open(PRE_COMMIT_YAML, 'w', encoding='UTF-8') as pre_commit_file:
    pre_commit_file.write(ordered_dump(config_data, **YAML_DUMP_KWARGS))
```

```diff
     sha: v0.3.5
     hooks:
     -   id: reorder-python-imports
-        args: [
-            '--remove-import', 'from __future__ import absolute_import',
-            '--remove-import', 'from __future__ import unicode_literals',
-        ]
+        args:
+        - --remove-import
+        - from __future__ import absolute_import
+        - --remove-import
+        - from __future__ import unicode_literals
```

**Comment by asottile** [comment]
Unfortunately yaml doesn't roundtrip because information is lost during parsing.

`pre-commit` does some (ick) jumping through hoops to make `pre-commit autoupdate` work nicely: https://github.com/pre-commit/pre-commit/blob/41d998f1c46f371c9977dcc9d31d7b42387ed74c/pre_commit/commands/autoupdate.py#L75-L106

I've heard good things about https://pypi.python.org/pypi/ruamel.yaml doing proper yaml round tripping, though last time I attempted to use it it was both (1) not mature enough and (2) didn't actually round trip properly either.

If you have some more specifics on what you're trying to auto-rewrite I might be able to help you out with it :)

**Comment by KevinHock** [comment]
I ended up just appending, (goal was installing a pre-commit hook automatically.)

**Comment by asottile** [comment]
I'm confused, @swiss484 and @KevinHock are you working on the same project and / or the same person?

**Comment by swiss484** [comment]
Same person :) I was just on this account. I think appending worked out well though, I tested it.

**Comment by asottile** [comment]
There's cases where appending won't work, but as long as they're following generally the same standard structure it should mostly work?

**Comment by KevinHock** [comment]
One case I thought might mess me up was whether or not having `repos:` as the first line would change the indentation but it turned out to be the same. What cases can you think of? Thanks for your help btw 👍

**Comment by asottile** [comment]
for instance it'll break this file:

```yaml
repos: [
    {repo: ..., sha: ..., hooks: [{id: ...}]},
]
```
