### ISSUE TITLE
sdist for 0.2.2?

### ISSUE THREAD

**Issue by ilovezfs** [asottile/aspy.yaml#5]
Is it deliberate that there's no sdist tarball for version 0.2.2 on PyPi? There appears to be an sdist for 0.2.1, but only a whl for 0.2.2

**Comment by asottile** [comment]
The reason at the time was to support pip 1.5 and python2.6 (strange as it sounds!).

Under pip 1.5, when installing from a source distribution, [environment markers](https://github.com/asottile/aspy.yaml/blob/2849f0f1082518de9f06e89a44e929b175b6d5f3/setup.py#L28) were not honored.

Since I no longer care to support python2.6, I'll update the packaging and release a new version.

The bit about poet not allowing **pure python** -none-any.whl files is quite broken.  That should really get fixed :)

**Comment by ilovezfs** [comment]
Thanks @asottile 

CC @tdsmith regarding the poet thing.

**Comment by asottile** [comment]
I've released 0.3.0
